### ISSUE TITLE
Error while the output differs

### ISSUE THREAD

**Issue by sjkeerthi** [s3h10r/iostat-plotter#1]
Hi 

I downloaded the and tried the iostat-plotter on my desk top where I could able to generate graph.

But when I try to get the iostat performance on my VM where resides in xenserver so where the output is little bit diffrent than the normal pasted below.

Linux 2.6.32-358.18.1.el6.x86_64 (cf14-job)     12/18/2014      _x86_64_        (8 CPU)

12/18/2014 07:00:10 AM
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           1.72    0.00    2.43    0.03    0.04   95.78

Device:         rrqm/s   wrqm/s     r/s     w/s    rMB/s    wMB/s avgrq-sz avgqu-sz   await  svctm  %util
dm-0              0.00     0.00    0.22    5.83     0.00     0.02     9.39     0.13   21.03   0.78   0.47

Error while executing the code with above output.

./iostat_plotter_article.py iostat.out 
iostat plotting script

input filename:  iostat.out

reading iostat output file ... 
Traceback (most recent call last):
  File "./iostat_plotter_article.py", line 361, in <module>
    svctm_list.append(float(currentline[12]));
IndexError: list index out of range

since I found when I run the iostats on my VM I couldn't get the output output of 
r_await w_await fields.

**Comment by s3h10r** [comment]
Hi, it seems to me that in your environment (xenserver) sysstat version 9 is installed. Can you confirm this (try `sysstat -V` on the machine gathering the iostat-data)? if so, please use `iostat_plotter_v3.py` - it supports sysstat V9 and V10 and should do what you want. :-) 

if this does not work please send me some more infos about your environment or at least an iostat-data example from your machine and i will see what i can do.

**Comment by s3h10r** [comment]
@sjkeerthi i'm closing this issue, please feel free to re-open if my suggestions from above are wrong.
